/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cinema;

import java.awt.Color;
import java.awt.event.ItemEvent;

/**
 *
 * @author Gabriel
 */
public class telaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastro
     */
    public telaCadastro() {
        initComponents();
        jtfChaveCadastro.setBackground(new Color (0,0,0,50));
        jtfRGCadastro.setBackground(new Color (0,0,0,50));
        jtfEmailCadastro.setBackground(new Color (0,0,0,50));
        jtfCEPCadastro.setBackground(new Color (0,0,0,50));
        jtfTelefoneCadastro.setBackground(new Color (0,0,0,50));
        jtfNomeCadastro.setBackground(new Color (0,0,0,50));
        jtfCPFCadastro.setBackground(new Color (0,0,0,50));
        jrbFemininoCadastro.setBackground(new Color (0,0,0,50));
        jrbMasculinoCadastro.setBackground(new Color (0,0,0,50));
        jpfSenha2Cadastro.setBackground(new Color (0,0,0,50));
        jpfSenhaCadastro.setBackground(new Color (0,0,0,50));
        jcbFuncionarioCadastro.setBackground(new Color (0,0,0,50));
        jlCadastrar.setBackground(new Color(0,0,0,200));
        jtfChaveCadastro.setVisible(false);
        
        buttonGroup2.add(jrbFemininoCadastro);
        buttonGroup2.add(jrbMasculinoCadastro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfChaveCadastro = new javax.swing.JTextField();
        jtfRGCadastro = new javax.swing.JTextField();
        jtfEmailCadastro = new javax.swing.JTextField();
        jtfCEPCadastro = new javax.swing.JTextField();
        jtfTelefoneCadastro = new javax.swing.JTextField();
        jtfNomeCadastro = new javax.swing.JTextField();
        jrbFemininoCadastro = new javax.swing.JRadioButton();
        jrbMasculinoCadastro = new javax.swing.JRadioButton();
        jpfSenhaCadastro = new javax.swing.JPasswordField();
        jcbFuncionarioCadastro = new javax.swing.JCheckBox();
        jpfSenha2Cadastro = new javax.swing.JPasswordField();
        jtfCPFCadastro = new javax.swing.JTextField();
        jlCadastrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastre-se");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 620, -1));

        jtfChaveCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfChaveCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfChaveCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfChaveCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfChaveCadastro.setText("Chave Funcionário");
        jtfChaveCadastro.setBorder(null);
        jtfChaveCadastro.setOpaque(false);
        jtfChaveCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfChaveCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(jtfChaveCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 180, 40));

        jtfRGCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfRGCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfRGCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfRGCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfRGCadastro.setText("Digite seu RG");
        jtfRGCadastro.setBorder(null);
        jtfRGCadastro.setOpaque(false);
        jPanel1.add(jtfRGCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 40));

        jtfEmailCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfEmailCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfEmailCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfEmailCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfEmailCadastro.setText("Digite seu E-Mail");
        jtfEmailCadastro.setBorder(null);
        jtfEmailCadastro.setOpaque(false);
        jPanel1.add(jtfEmailCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, 40));

        jtfCEPCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfCEPCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfCEPCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfCEPCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCEPCadastro.setText("Digite seu CEP");
        jtfCEPCadastro.setBorder(null);
        jtfCEPCadastro.setOpaque(false);
        jPanel1.add(jtfCEPCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 180, 40));

        jtfTelefoneCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfTelefoneCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfTelefoneCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfTelefoneCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfTelefoneCadastro.setText("Digite seu Telefone");
        jtfTelefoneCadastro.setBorder(null);
        jtfTelefoneCadastro.setOpaque(false);
        jPanel1.add(jtfTelefoneCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 180, 40));

        jtfNomeCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfNomeCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfNomeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfNomeCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNomeCadastro.setText("Digite seu nome");
        jtfNomeCadastro.setBorder(null);
        jtfNomeCadastro.setOpaque(false);
        jPanel1.add(jtfNomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, 40));

        jrbFemininoCadastro.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jrbFemininoCadastro);
        jrbFemininoCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jrbFemininoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jrbFemininoCadastro.setText("Feminino");
        jrbFemininoCadastro.setBorder(null);
        jrbFemininoCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbFemininoCadastro.setPreferredSize(new java.awt.Dimension(149, 22));
        jPanel1.add(jrbFemininoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 180, 40));

        jrbMasculinoCadastro.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jrbMasculinoCadastro);
        jrbMasculinoCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jrbMasculinoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jrbMasculinoCadastro.setText("Masculino");
        jrbMasculinoCadastro.setBorder(null);
        jrbMasculinoCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbMasculinoCadastro.setPreferredSize(new java.awt.Dimension(149, 22));
        jrbMasculinoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMasculinoCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(jrbMasculinoCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 40));

        jpfSenhaCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jpfSenhaCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jpfSenhaCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jpfSenhaCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpfSenhaCadastro.setText("jPasswordField1");
        jpfSenhaCadastro.setBorder(null);
        jPanel1.add(jpfSenhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 180, 40));

        jcbFuncionarioCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jcbFuncionarioCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jcbFuncionarioCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jcbFuncionarioCadastro.setText("Funcionário");
        jcbFuncionarioCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcbFuncionarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFuncionarioCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(jcbFuncionarioCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 180, 40));

        jpfSenha2Cadastro.setBackground(new java.awt.Color(0, 0, 0));
        jpfSenha2Cadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jpfSenha2Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        jpfSenha2Cadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpfSenha2Cadastro.setText("jPasswordField1");
        jpfSenha2Cadastro.setBorder(null);
        jPanel1.add(jpfSenha2Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 180, 40));

        jtfCPFCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfCPFCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfCPFCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfCPFCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCPFCadastro.setText("Digite seu CPF");
        jtfCPFCadastro.setBorder(null);
        jtfCPFCadastro.setOpaque(false);
        jPanel1.add(jtfCPFCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, 40));

        jlCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        jlCadastrar.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jlCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jlCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCadastrar.setText("Cadastrar");
        jlCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlCadastrar.setOpaque(true);
        jPanel1.add(jlCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastro.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbMasculinoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMasculinoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMasculinoCadastroActionPerformed

    private void jcbFuncionarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFuncionarioCadastroActionPerformed
         if(jcbFuncionarioCadastro.isSelected()){
         jtfChaveCadastro.setVisible(true);
         } else{
             jtfChaveCadastro.setVisible(false);
         }
    }//GEN-LAST:event_jcbFuncionarioCadastroActionPerformed

    private void jtfChaveCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfChaveCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfChaveCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbFuncionarioCadastro;
    private javax.swing.JLabel jlCadastrar;
    private javax.swing.JPasswordField jpfSenha2Cadastro;
    private javax.swing.JPasswordField jpfSenhaCadastro;
    private javax.swing.JRadioButton jrbFemininoCadastro;
    private javax.swing.JRadioButton jrbMasculinoCadastro;
    private javax.swing.JTextField jtfCEPCadastro;
    private javax.swing.JTextField jtfCPFCadastro;
    private javax.swing.JTextField jtfChaveCadastro;
    private javax.swing.JTextField jtfEmailCadastro;
    private javax.swing.JTextField jtfNomeCadastro;
    private javax.swing.JTextField jtfRGCadastro;
    private javax.swing.JTextField jtfTelefoneCadastro;
    // End of variables declaration//GEN-END:variables
}
