/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cinema;

import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author Aluno
 */
public class telaCadastroFilmes extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroFilmes
     */
    public telaCadastroFilmes() {
        
        initComponents();
        jbCadastrarFilme.setBackground(new Color(0,0,0,200));
        jtfDuracaoFilmeCadastro.setBackground(new Color(0,0,0,50));
        jtfAtoresFilmeCadastro.setBackground(new Color(0,0,0,50));
        jtfCensuraFilmeCadastro.setBackground(new Color(0,0,0,50));
        jtfNomeFilmeCadastro.setBackground(new Color(0,0,0,50));
        jtfAnoFilmeCadastro.setBackground(new Color(0,0,0,50));
        jtaSinopseFilmeCadastro.setBackground(new Color(0,0,0,50));
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeFilmeCadastro = new javax.swing.JTextField();
        jtfAnoFilmeCadastro = new javax.swing.JTextField();
        jtfAtoresFilmeCadastro = new javax.swing.JTextField();
        jtfDuracaoFilmeCadastro = new javax.swing.JTextField();
        jtfCensuraFilmeCadastro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSinopseFilmeCadastro = new javax.swing.JTextArea();
        jbCadastrarFilme = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastre-se");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cadastrar Filmes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 620, -1));

        jtfNomeFilmeCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfNomeFilmeCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfNomeFilmeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfNomeFilmeCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNomeFilmeCadastro.setText("Nome do Filme");
        jtfNomeFilmeCadastro.setBorder(null);
        jtfNomeFilmeCadastro.setOpaque(false);
        jPanel1.add(jtfNomeFilmeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, 40));

        jtfAnoFilmeCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfAnoFilmeCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfAnoFilmeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfAnoFilmeCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfAnoFilmeCadastro.setText("Ano de Lançamento");
        jtfAnoFilmeCadastro.setBorder(null);
        jtfAnoFilmeCadastro.setOpaque(false);
        jPanel1.add(jtfAnoFilmeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, 40));

        jtfAtoresFilmeCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfAtoresFilmeCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfAtoresFilmeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfAtoresFilmeCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfAtoresFilmeCadastro.setText("Principais Atores");
        jtfAtoresFilmeCadastro.setBorder(null);
        jtfAtoresFilmeCadastro.setOpaque(false);
        jPanel1.add(jtfAtoresFilmeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 40));

        jtfDuracaoFilmeCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfDuracaoFilmeCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfDuracaoFilmeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfDuracaoFilmeCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDuracaoFilmeCadastro.setText("Duração do Filme");
        jtfDuracaoFilmeCadastro.setBorder(null);
        jtfDuracaoFilmeCadastro.setOpaque(false);
        jPanel1.add(jtfDuracaoFilmeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 180, 40));

        jtfCensuraFilmeCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jtfCensuraFilmeCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtfCensuraFilmeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtfCensuraFilmeCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCensuraFilmeCadastro.setText("Censura do Filme");
        jtfCensuraFilmeCadastro.setBorder(null);
        jtfCensuraFilmeCadastro.setOpaque(false);
        jPanel1.add(jtfCensuraFilmeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 180, 40));

        jtaSinopseFilmeCadastro.setColumns(20);
        jtaSinopseFilmeCadastro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jtaSinopseFilmeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jtaSinopseFilmeCadastro.setRows(5);
        jtaSinopseFilmeCadastro.setText("Sinopse do Filme");
        jtaSinopseFilmeCadastro.setBorder(null);
        jtaSinopseFilmeCadastro.setOpaque(false);
        jScrollPane1.setViewportView(jtaSinopseFilmeCadastro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 480, -1));

        jbCadastrarFilme.setBackground(new java.awt.Color(0, 0, 0));
        jbCadastrarFilme.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jbCadastrarFilme.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastrarFilme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbCadastrarFilme.setText("Cadastrar");
        jbCadastrarFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbCadastrarFilme.setOpaque(true);
        jPanel1.add(jbCadastrarFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastro.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbCadastrarFilme;
    private javax.swing.JTextArea jtaSinopseFilmeCadastro;
    private javax.swing.JTextField jtfAnoFilmeCadastro;
    private javax.swing.JTextField jtfAtoresFilmeCadastro;
    private javax.swing.JTextField jtfCensuraFilmeCadastro;
    private javax.swing.JTextField jtfDuracaoFilmeCadastro;
    private javax.swing.JTextField jtfNomeFilmeCadastro;
    // End of variables declaration//GEN-END:variables
}
